openapi: 3.0.1
info:
    title: Cache-POC
    version: 0.3.0
    description: '<p>This is the Cache-POC openApi specifications</p>'
servers:
    - url: http://localhost:4000/api
      description: Local
paths:
    /orders:
        get:
            tags:
                - Orders List
            operationId: list-orders
            summary: Return a list of items
            description: Returns a list of items
            responses:
                200:
                    description: successful operation
