openapi: 3.0.1
info:
    title: Rappi Connector
    version: 0.3.0
    description: '<p>This is the Rappi Connector openApi specifications</p>'
servers:
    - url: http://localhost:3000/api
      description: Local
    - url: https://k8s.homolog.quiq.delivery/orders-service/api
      description: Homolog
paths:
    /orders:
        get:
            tags:
                - Orders List
            operationId: list-orders
            summary: Return a list of items
            description: Returns a list of items
            responses:
                200:
                    description: successful operation
